apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-finance
  labels:
    app: backend-finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-finance
  template:
    metadata:
      labels:
        app: backend-finance
    spec:
      containers:
      - name: backend-finance
        image: asia-northeast1-docker.pkg.dev/erp-project-8386/arsneonci-repo/backend-finance:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "development"
        - name: DB_HOST
          value: "postgres-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: erp-db-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          value: "finance_db"
        - name: REDIS_HOST
          value: "redis-cache"
        - name: REDIS_PORT
          value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-finance-svc
spec:
  type: ClusterIP
  selector:
    app: backend-finance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080