apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: portal.arsneonci.space
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port: 
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: erp-frontend
            port: 
              number: 3000