spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc: # Bắt buộc phải có chữ 'mvc' vì bạn dùng gateway-server-webmvc
        routes:
          - id: crm-service-route
            uri: http://backend-crm-svc:80
            predicates:
              - Path=/api/crm/**
          - id: sales-service-route
            uri: http://backend-sales-svc:80
            predicates:
              - Path=/api/sales/**
          - id: ai-face-route
            uri: http://ai-face-recognition-svc:80
            predicates:
              - Path=/api/ai-face/**
server:
  port: 8080