spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: sales-service
          uri: http://backend-sales:8080  # Tên K8s Service
          predicates:
            - Path=/api/sales/**
        - id: crm-service
          uri: http://backend-crm:8080
          predicates:
            - Path=/api/crm/**
        - id: ai-face-service
          uri: http://ai-face-recognition:8000
          predicates:
            - Path=/api/ai-face/**
server:
  port: 8080